<<<<<<< HEAD
version: "3.8"

services:
  webscraping-aero:
    build: .
    container_name: webscraping-aero
    ports:
      - "3010:3000"
    restart: unless-stopped

=======
version: "3.8"

services:
  webscraping-aero:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    restart: unless-stopped
    shm_size: "1gb"
>>>>>>> 5f8ed62 (ajusta seletor e compose do scraping-aero)
