version: "3.8"

services:
  webscraping-aero:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3010:3000"  # 3010 = porta externa na VPS / 3000 = porta interna do Node
    shm_size: "1gb"
